version: '3.3'

services:
  untrunc:
    build: untrunc
    container_name: untrunc
    command: python3 app.py
    volumes:
      - ./untrunc/app.py:/app.py
      - Jejaljejal:/data
    networks:
      - ssafy-net
    environment:
      - FLASK_DATA_PATH=/data/WebSocket
      - FLASK_FILE_PERIOD=15000
      - FLASK_FILE_DUPLICATE=0
    ports:
      - 8300:8000

  backend:
      build: jejal
      container_name: jejal
      ports:
        - 8080:8080 # Dockerfile에서 EXPOSE 8080 추가하였기 때문에 포트 매핑 확인
      networks:
        - ssafy-net
      volumes:
      - ./jejal/build/libs/*.jar:/app.jar # 이 경로에 Dockerfile과 소스 코드가 있어야 함
      entrypoint: ["java", "-jar", "/app/app.jar"] # entrypoint는 Dockerfile 설정을 사용합니다

volumes:
  Jejaljejal:
    external: false

networks:
  ssafy-net:
    external: true
